Name: locust

image:
  repository: greenbirdit/locust
  tag: 0.9.0
  pullPolicy: IfNotPresent

service:
  name: master-web
  type: ClusterIP
  externalPort: 8089
  internalPort: 8089
  nodePort: 0
  annotations: {}
  extraLabels: {}
master:
  config:
    target-host: https://site.example.com
  resources:
    limits:
      cpu: 3500m
    requests:
      cpu: 1000m

worker:
  config:
    # all files from tasks folder are mounted under `/locust-tasks`
    locust-script: "/locust-tasks/example.py"
  minReplicas: 5
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80
  resources:
    limits:
      cpu: 3500m
      memory: 5G
    requests:
      cpu: 2000m
      memory: 512M
