apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "locust.worker" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "locust.worker" . }}
  minReplicas: {{ default 1 .Values.worker.minReplicas }}
  maxReplicas: {{ default 3 .Values.worker.maxReplicas }}
  targetCPUUtilizationPercentage: {{ default 60 .Values.worker.targetCPUUtilizationPercentage }}
